### ISSUE TITLE
max_age value incorrectly set

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/altis-cloud#546] opened 2022-01-18 14:11 UTC
On some environments, the `$batcache->cache['max_age']` value seems to be incorrectly set. 

The full warning in logs is shown as:
```
E_NOTICE: Trying to access array offset on value of type bool
/usr/src/app/vendor/humanmade/batcache/advanced-cache.php:577
```

While the error is relatively benign, it does cause a lot of noise, particularly in XRay. DM for XRay trace samples.

**Comment by roborourke** [comment] 2022-01-31 11:57
@owaincuvelier can you confirm if they have the latest patch version of the cloud module?

@robindevitt this seems familiar, did you do a fix for this recently?

**Comment by rmccue** [comment] 2022-01-31 12:01
@roborourke https://github.com/humanmade/batcache/issues/22 - no existing Altis tracking issue afaik though

**Comment by roborourke** [comment] 2022-01-31 12:15
Here we are:

- https://github.com/humanmade/altis-cloud/issues/484

Closing as a duplicate of #484, solution is to ensure you are running Batcache 1.3.5 or higher which is available to Altis v6 and up.

Run `composer update --with-all-dependencies` to update.

**Closed by roborourke** 2022-01-31 12:15 UTC
Labels: bug, should have
