### ISSUE TITLE
Default to Composer v2 for dependency management

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#350] opened 2021-03-23 16:03 UTC
Composer v2 is significantly faster than v1 when installing dependencies. Although v1 isn't going away any time soon, the preparations for its deprecation have started: https://blog.packagist.com/deprecating-composer-1-support/.

It would be great to opt in to using Composer v2 as part of Altis deployment so we can update our dependencies to their v2 compatible versions where necessary.

**Comment by roborourke** [comment] 2021-04-01 17:42
Hey @johnbillion, I'm not totally sure what you mean by this, what's getting in the way of using Composer v2?

We do need to update the build container to default to Composer v2 but in the mean time you can do the following in the `.build-scipt` before any other steps:

```
composer self-update --2
```

**Comment by johnbillion** [comment] 2021-04-02 08:28
> what's getting in the way of using Composer v2?

I wasn't aware that running a self-update within the build script was an option. I don't know what else Composer is used for as part of the build and deployment.

If this is safe to do, then great!

**Comment by roborourke** [comment] 2021-04-22 13:01
Noting here that we should still do the following:

- [ ] Update the build container to default to Composer v2
- [ ] Provide documentation for switching to v1 if required

**Comment by rmccue** [comment] 2021-05-06 15:21
Duplicate of https://github.com/humanmade/product-dev/issues/651

**Closed by rmccue** 2021-05-06 15:21 UTC
Labels: must have
