### ISSUE TITLE
PHP notices/warnings are not buffered before sending to CloudWatch, causing excessive HTTP requests

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cloud#251] opened 2020-10-16 11:21 UTC
Steps to reproduce:
1. Create a function that causes a notice/warning
2. Call this function in a loop that is called a bunch of times (e.g. 100)
3. Observe majority of page load time spent sending data to CloudWatch in `error_handler` and `send_buffered_errors`

For non-critical errors handled by the error handler, these should be buffered and sent as part of the final data, or at least chunked, so as not to dominate the page load times.

Reference [ZD4154](https://dashboard.altis-dxp.com/#/support/ticket/4154/).

Acceptance criteria:

- [ ] ...

**Comment by nathanielks** [comment] 2020-10-16 15:49
I've been doing some research on changing how we log these to CloudWatch. I'm looking into how we can either log to stdout or similar and have a daemon route to separate log streams so that the logging itself isn't handled by the web request. It looks like I might be able to make use of AWS' Fluent Bit to route logs from a single container to multiple destinations, but I haven't been able to confirm this yet.

**Comment by jennybeaumont** [comment] 2020-11-04 15:38
@nathanielks are you actively working on this? If so, can we assigned it to you and put it In Progress?

**Comment by nathanielks** [comment] 2020-11-04 19:28
@jennybeaumont does working on this when I don't have support tickets qualify? Once I'm back on the product rotation, I'll be looking at this more closely. For reference, this is the same/related to the epic I created here: https://app.zenhub.com/workspaces/cloud-5d56818b5a29b300018e41bf/issues/humanmade/terraform-app-stack/715. I'm tracking that on the Cloud board, currently. How would you like this handled, @jennybeaumont ?

**Comment by jennybeaumont** [comment] 2020-11-05 17:38
@nathanielks thanks for the prompt reply! All good, was just checking 🙂 came up in refinement yesterday as we were triaging new items. Have moved it to backlog. Should you pick it up again, just pop it in In Progress for visibility. Ta!

**Comment by jennybeaumont** [comment] 2021-02-02 16:45
Duplicate of https://github.com/humanmade/terraform-app-stack/issues/715

**Closed by jennybeaumont** 2021-02-02 16:45 UTC
Labels: bug, should have
